# Normally we would also import ZMK, but since Aekeynox already depends on it,
# we just let it deal with it (i.e. import it as one of its dependencies).

manifest:
  remotes:
    - name: OneDeadKey
      url-base: https://github.com/OneDeadKey
  projects:
    - name: zmk-config-aekeynox
      remote: OneDeadKey
      revision: main
      import: config/west.yml
  self:
    path: config
